// <auto-generated />
using System;
using Hyden.Api.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hyden.Api.Infrastructure.Migrations
{
    [DbContext(typeof(HydenDbContext))]
    [Migration("20251028165018_AddEntities")]
    partial class AddEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hyden.Api.Domain.Entities.IrrigationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("MoistureAfter")
                        .HasColumnType("double precision");

                    b.Property<double>("MoistureBefore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SmartPotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WaterAmount")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SmartPotId");

                    b.ToTable("IrrigationHistories", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Domain.Entities.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("PlantSpecId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SmartPotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlantSpecId");

                    b.HasIndex("SmartPotId");

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Domain.Entities.PlantSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommonName")
                        .HasColumnType("text");

                    b.Property<double>("IdealMoistureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("IdealMoistureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("IdealTempMax")
                        .HasColumnType("double precision");

                    b.Property<double>("IdealTempMin")
                        .HasColumnType("double precision");

                    b.Property<string>("Light")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ScientificName")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WateringFrequency")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlantSpecs", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Domain.Entities.SmartPot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConnectionStatus")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastIrrigation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("LastSoilMoisture")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<double>("ReservoirLevel")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("SmartPots", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Domain.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifications", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Domain.Entities.IrrigationHistory", b =>
                {
                    b.HasOne("Hyden.Api.Domain.Entities.SmartPot", "SmartPot")
                        .WithMany()
                        .HasForeignKey("SmartPotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartPot");
                });

            modelBuilder.Entity("Hyden.Api.Domain.Entities.Plant", b =>
                {
                    b.HasOne("Hyden.Api.Domain.Entities.PlantSpec", "PlantSpec")
                        .WithMany()
                        .HasForeignKey("PlantSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hyden.Api.Domain.Entities.SmartPot", "SmartPot")
                        .WithMany()
                        .HasForeignKey("SmartPotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantSpec");

                    b.Navigation("SmartPot");
                });

            modelBuilder.Entity("Hyden.Api.Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("Hyden.Api.Domain.Entities.User", "UserNotified")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNotified");
                });
#pragma warning restore 612, 618
        }
    }
}
