// <auto-generated />
using System;
using Hyden.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hyden.Api.Migrations
{
    [DbContext(typeof(HydenDbContext))]
    [Migration("20251122055320_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hyden.Api.Core.Models.IrrigationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("IRRIGATION_HISTORY_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<double>("MoistureAfter")
                        .HasColumnType("double precision")
                        .HasColumnName("MOISTURE_AFTER");

                    b.Property<double>("MoistureBefore")
                        .HasColumnType("double precision")
                        .HasColumnName("MOISTURE_BEFORE");

                    b.Property<Guid>("SmartPotId")
                        .HasColumnType("uuid")
                        .HasColumnName("SMART_POT_ID");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("TIMESTAMP");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<double>("WaterAmount")
                        .HasColumnType("double precision")
                        .HasColumnName("WATER_AMOUNT");

                    b.HasKey("Id");

                    b.HasIndex("SmartPotId");

                    b.ToTable("IRRIGATION_HISTORIES", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Core.Models.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PLANT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("NAME");

                    b.Property<Guid>("PlantSpecificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("PLANT_SPECIFICATION_ID");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("REGISTRATION_DATE");

                    b.Property<Guid>("SmartPotId")
                        .HasColumnType("uuid")
                        .HasColumnName("SMART_POT_ID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("PlantSpecificationId");

                    b.HasIndex("SmartPotId");

                    b.ToTable("PLANTS", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Core.Models.PlantSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PLANT_SPECIFICATION_ID");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("COMMON_NAME");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<double>("IdealMoistureMax")
                        .HasColumnType("double precision")
                        .HasColumnName("IDEAL_MOISTURE_MAX");

                    b.Property<double>("IdealMoistureMin")
                        .HasColumnType("double precision")
                        .HasColumnName("IDEAL_MOISTURE_MIN");

                    b.Property<double>("IdealTempMax")
                        .HasColumnType("double precision")
                        .HasColumnName("IDEAL_TEMP_MAX");

                    b.Property<double>("IdealTempMin")
                        .HasColumnType("double precision")
                        .HasColumnName("IDEAL_TEMP_MIN");

                    b.Property<string>("Light")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LIGHT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("NOTES");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SCIENTIFIC_NAME");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("TYPE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("WateringFrequency")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasColumnName("WATERING_FREQUENCY");

                    b.HasKey("Id");

                    b.ToTable("PLANT_SPECS", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Core.Models.SmartPot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("SMART_POT_ID");

                    b.Property<bool>("ConnectionStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("CONNECTION_STATUS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("LastIrrigation")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LAST_IRRIGATION");

                    b.Property<double>("LastSoilMoisture")
                        .HasColumnType("double precision")
                        .HasColumnName("LAST_SOIL_MOISTURE");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("LOCATION");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasColumnName("QR_CODE");

                    b.Property<double>("ReservoirLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("RESERVOIR_LEVEL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("QrCode")
                        .IsUnique();

                    b.ToTable("SMART_POTS", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("EMAIL_CONFIRMED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("NAME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Core.Models.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("USER_NOTIFICATION_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("IS_READ");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("MESSAGE");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("SENT_AT");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("TITLE");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("TYPE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("UPDATED_AT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("USER_NOTIFICATIONS", (string)null);
                });

            modelBuilder.Entity("Hyden.Api.Core.Models.IrrigationHistory", b =>
                {
                    b.HasOne("Hyden.Api.Core.Models.SmartPot", "SmartPot")
                        .WithMany()
                        .HasForeignKey("SmartPotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartPot");
                });

            modelBuilder.Entity("Hyden.Api.Core.Models.Plant", b =>
                {
                    b.HasOne("Hyden.Api.Core.Models.PlantSpecification", "PlantSpecification")
                        .WithMany()
                        .HasForeignKey("PlantSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hyden.Api.Core.Models.SmartPot", "SmartPot")
                        .WithMany()
                        .HasForeignKey("SmartPotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantSpecification");

                    b.Navigation("SmartPot");
                });

            modelBuilder.Entity("Hyden.Api.Core.Models.UserNotification", b =>
                {
                    b.HasOne("Hyden.Api.Core.Models.User", "UserNotified")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNotified");
                });
#pragma warning restore 612, 618
        }
    }
}
